// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: packet.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:

	packet.proto

It has these top-level messages:

	Request
	Response
	Counter
	Gauge
	Summary
	Metric
	Metrics
*/
package proto

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
